### ISSUE TITLE
Expose firmware and vehicle types in graphql

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#74]
Graphql should show the firmware type (px4, ardupilot etc), and the vehicle type (copter, plane etc)

**Comment by SamuelDudley** [comment]
info returned from mavros (per connected vehicle):
```
    success: True
    vehicles: 
      - 
        header: 
          seq: 0
          stamp: 
            secs: 1547036032
            nsecs: 255436314
          frame_id: ''
        available_info: 3
        sysid: 1
        compid: 1
        autopilot: 3
        type: 2
        system_status: 4
        base_mode: 217
        custom_mode: 17
        mode: "BRAKE"
        mode_id: 17
        capabilities: 15311
        flight_sw_version: 50790400
        middleware_sw_version: 0
        os_sw_version: 0
        board_version: 0
        vendor_id: 0
        product_id: 0
        uid: 0
```

`autopilot` field is then being parsed to return the frame type e.g. `ArduCopter`
